name: Finn360 Backend CI/CD

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'finn360BE/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./finn360BE

    steps:
    - name: Kodu Çek
      uses: actions/checkout@v4

    - name: Java JDK 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Maven ile Derle (Testleri Atla)
      run: mvn clean package -DskipTests

    - name: Docker Hub'a Giriş Yap
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker İmajını Oluştur ve Yükle
      # "seninkullaniciadin/imajadi:latest" yapısını kendi bilgilerine göre düzenleyebilirsin
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/finn360-backend:latest -t ${{ secrets.DOCKER_USERNAME }}/finn360-backend:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/finn360-backend:latest
